const GET_DATA_REQUESTED = 'GET_DATA_REQUESTED';
const GET_DATA_DONE = 'GET_DATA_DONE';
const GET_DATA_FAILED = 'GET_DATA_FAILED';

export default {
  GET_DATA_REQUESTED,
  GET_DATA_DONE,
  GET_DATA_FAILED,
};
